"""add sendor address

Revision ID: 3a0088d9006d
Revises: c94602c9e293
Create Date: 2025-09-27 01:59:31.002085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3a0088d9006d"
down_revision: Union[str, Sequence[str], None] = "c94602c9e293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

constraint_name = "fk_message_sender_address_id_address"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sender_address_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(constraint_name, "address", ["sender_address_id"], ["id"], ondelete="SET NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_="foreignkey")
        batch_op.drop_column("sender_address_id")

    # ### end Alembic commands ###
