"""tables

Revision ID: 9fe35b6e9809
Revises:
Create Date: 2025-09-08 13:52:03.398983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "9fe35b6e9809"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_address_email_address"), "address", ["email_address"], unique=True)
    op.create_table(
        "message",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_sent", sa.DateTime(), nullable=True),
        sa.Column("rfc822_message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_received", sa.DateTime(), nullable=False),
        sa.Column("in_reply_to", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("references_list", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_replied", sa.Boolean(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("is_forwarded", sa.Boolean(), nullable=False),
        sa.Column("vendor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_date_received"), "message", ["date_received"], unique=False)
    op.create_index(op.f("ix_message_rfc822_message_id"), "message", ["rfc822_message_id"], unique=True)
    op.create_table(
        "priorityword",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_priorityword_word"), "priorityword", ["word"], unique=True)
    op.create_table(
        "tag",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_tag_name"), "tag", ["tag_name"], unique=True)
    op.create_table(
        "messageaddressmap",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("address_type", sa.Enum("FROM", "TO", "CC", "BCC", name="addresstype"), nullable=False),
        sa.CheckConstraint("address_type in ('from','to','cc','bcc')", name="ck_message_address_map_address_type"),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "address_id", "address_type"),
    )
    op.create_table(
        "messagepart",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mime_subtype", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_disposition", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("part_order", sa.Integer(), nullable=True),
        sa.Column("is_attachment", sa.Boolean(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("parent_part_id", sa.Integer(), nullable=True),
        sa.Column("content_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_part_id"], ["messagepart.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_message_part_message_id_is_attachment_part_order",
        "messagepart",
        ["message_id", "is_attachment", "part_order"],
        unique=False,
    )
    op.create_index(op.f("ix_messagepart_content_id"), "messagepart", ["content_id"], unique=False)
    op.create_index(op.f("ix_messagepart_message_id"), "messagepart", ["message_id"], unique=False)
    op.create_table(
        "messagetagmap",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "tag_id"),
    )
    op.create_table(
        "messageword",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("word", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tf", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "word"),
    )
    op.create_index(op.f("ix_messageword_word"), "messageword", ["word"], unique=False)
    op.create_table(
        "priorityperson",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_priorityperson_address_id"), "priorityperson", ["address_id"], unique=True)
    op.create_table(
        "summary",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_summary_message_id"), "summary", ["message_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_summary_message_id"), table_name="summary")
    op.drop_table("summary")
    op.drop_index(op.f("ix_priorityperson_address_id"), table_name="priorityperson")
    op.drop_table("priorityperson")
    op.drop_index(op.f("ix_messageword_word"), table_name="messageword")
    op.drop_table("messageword")
    op.drop_table("messagetagmap")
    op.drop_index(op.f("ix_messagepart_message_id"), table_name="messagepart")
    op.drop_index(op.f("ix_messagepart_content_id"), table_name="messagepart")
    op.drop_index("ix_message_part_message_id_is_attachment_part_order", table_name="messagepart")
    op.drop_table("messagepart")
    op.drop_table("messageaddressmap")
    op.drop_index(op.f("ix_tag_tag_name"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_priorityword_word"), table_name="priorityword")
    op.drop_table("priorityword")
    op.drop_index(op.f("ix_message_rfc822_message_id"), table_name="message")
    op.drop_index(op.f("ix_message_date_received"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_address_email_address"), table_name="address")
    op.drop_table("address")
    # ### end Alembic commands ###
